### ISSUE TITLE
box shadow

### ISSUE THREAD

**Issue by kozimov786** [rustami-dastan/zendit#3]
<img width="856" alt="Screen Shot 2021-04-13 at 14 24 50" src="https://user-images.githubusercontent.com/79497700/114530104-1224db00-9c64-11eb-95ba-6178e1c84a9d.png">
expexted state
<img width="443" alt="Screen Shot 2021-04-13 at 14 24 06" src="https://user-images.githubusercontent.com/79497700/114530166-1f41ca00-9c64-11eb-82cc-11127582afb3.png">
current state
you don't put box shadow on the card

**Comment by rustami-dastan** [comment]
problem solved.
