### ISSUE TITLE
forget to put icon

### ISSUE THREAD

**Issue by kozimov786** [rustami-dastan/zendit#4]
<img width="539" alt="Screen Shot 2021-04-13 at 14 26 41" src="https://user-images.githubusercontent.com/79497700/114530566-7f387080-9c64-11eb-9c61-8f8d07a2cfaf.png">
current state
<img width="539" alt="Screen Shot 2021-04-13 at 14 26 52" src="https://user-images.githubusercontent.com/79497700/114530621-89f30580-9c64-11eb-8dba-49ff297a1055.png">
expected state

**Comment by rustami-dastan** [comment]
problem solved.
